name: tyoskinviinibaari
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9003900731913745
title: Ty√∂skin Viinibaari
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191917'
    - '#FEFCFD'
    - '#A26435'
    - '#5F3C28'
    - '#CF8D4F'
  brandStrength: 0.8125
  lightness: 0.5471491820644587
  saturation: 0.0721229356713593
  rhythmicContrast: 0.3485990336630493
purpose: []
